import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { mkdir, readdir, unlink, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { z } from 'zod';

import { Either } from '../Either';

type StorageEntry<TSchema extends z.ZodObject> = {
  data: z.output<TSchema>;
  createdAt: string;
};
type StorageMap<TSchema extends z.ZodObject> = Record<RepositoryId, StorageEntry<TSchema>>;

const RepositoryIdSchema = z.string().min(1).brand<'RepositoryId'>();

export type RepositoryId = z.output<typeof RepositoryIdSchema>;
export type RepositoryError = unknown;

export type StoredRow<TSchema extends z.ZodObject> = {
  id: RepositoryId;
  data: z.output<TSchema>;
  createdAt: string;
};

export type Repository<TSchema extends z.ZodObject> = {
  getAll(): Promise<Either<RepositoryError, StoredRow<TSchema>[]>>;
  getById(id: RepositoryId): Promise<Either<RepositoryError, StoredRow<TSchema> | undefined>>;
  create(data: z.input<TSchema>): Promise<Either<RepositoryError, StoredRow<TSchema>>>;
  update(id: RepositoryId, data: z.input<TSchema>): Promise<Either<RepositoryError, void>>;
  delete(id: RepositoryId): Promise<Either<RepositoryError, void>>;
};

const MODEL_NAME_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const YANDEX_DISK_API_BASE_URL = 'https://cloud-api.yandex.net/v1/disk';
const APP_FOLDER_PATH_PREFIX = 'app:/';
const WAL_FOLDER_PATH = join(process.cwd(), 'wals');
const WAL_RETENTION_MS = 7 * 24 * 60 * 60 * 1000;

type YandexLinkResponse = {
  href?: unknown;
  method?: unknown;
  templated?: unknown;
};

type YandexErrorResponse = {
  error?: unknown;
  description?: unknown;
  message?: unknown;
};

export function createRepositoryFromSchema<TSchema extends z.ZodObject>(
  name: string,
  schema: TSchema
): Either<RepositoryError, Repository<TSchema>> {
  if (!MODEL_NAME_PATTERN.test(name)) {
    return Either.left(`Model name "${name}" must be a kebab-case slug.`);
  }

  if (Object.prototype.hasOwnProperty.call(schema.shape, 'id')) {
    return Either.left(
      'Repository schemas must not define an id field; ids are generated by the repository.'
    );
  }

  const storagePath = `${APP_FOLDER_PATH_PREFIX}${name}.json`;
  const storageSchema = createStorageSchema(schema);

  const repository: Repository<TSchema> = {
    async getAll() {
      const storageResult = await readStorage(storagePath, storageSchema);

      if (Either.isLeft(storageResult)) {
        return storageResult;
      }

      return Either.right(storageToRows(storageResult.value));
    },

    async getById(id: RepositoryId) {
      const storageResult = await readStorage(storagePath, storageSchema);

      if (Either.isLeft(storageResult)) {
        return storageResult;
      }

      const entry = storageResult.value[id];

      if (entry === undefined) {
        return Either.right(undefined);
      }

      return Either.right({
        id,
        data: entry.data,
        createdAt: entry.createdAt
      });
    },

    async create(data: z.input<TSchema>) {
      const storageResult = await readStorage(storagePath, storageSchema);

      if (Either.isLeft(storageResult)) {
        return storageResult;
      }

      const dataResult = parseInputData(data, schema);

      if (Either.isLeft(dataResult)) {
        return dataResult;
      }

      const id = createRepositoryId();
      const entry = {
        data: dataResult.value,
        createdAt: new Date().toISOString()
      };

      storageResult.value[id] = entry;

      const writeResult = await writeStorage(storagePath, storageResult.value);

      if (Either.isLeft(writeResult)) {
        return writeResult;
      }

      return Either.right({
        id,
        data: entry.data,
        createdAt: entry.createdAt
      });
    },

    async update(id: RepositoryId, data: z.input<TSchema>) {
      const storageResult = await readStorage(storagePath, storageSchema);

      if (Either.isLeft(storageResult)) {
        return storageResult;
      }

      const currentEntry = storageResult.value[id];

      if (currentEntry === undefined) {
        return Either.left(`Cannot update missing row "${id}".`);
      }

      const dataResult = parseInputData(data, schema);

      if (Either.isLeft(dataResult)) {
        return dataResult;
      }

      currentEntry.data = dataResult.value;

      return writeStorage(storagePath, storageResult.value);
    },

    async delete(id: RepositoryId) {
      const storageResult = await readStorage(storagePath, storageSchema);

      if (Either.isLeft(storageResult)) {
        return storageResult;
      }

      if (storageResult.value[id] === undefined) {
        return Either.left(`Cannot delete missing row "${id}".`);
      }

      delete storageResult.value[id];

      return writeStorage(storagePath, storageResult.value);
    }
  };

  return Either.right(repository);
}

function createStorageSchema<TSchema extends z.ZodObject>(
  schema: TSchema
): z.ZodType<StorageMap<TSchema>> {
  const storageSchema = z.record(
    RepositoryIdSchema,
    z.object({
      data: schema,
      createdAt: z.iso.datetime({ offset: true })
    })
  );

  return z.custom<StorageMap<TSchema>>((value) => storageSchema.safeParse(value).success);
}

async function readStorage<TStorageSchema extends z.ZodType>(
  storagePath: string,
  storageSchema: TStorageSchema
): Promise<Either<RepositoryError, z.output<TStorageSchema>>> {
  const fileContentsResult = await downloadStorage(storagePath);

  if (Either.isLeft(fileContentsResult)) {
    return fileContentsResult;
  }

  let parsed: unknown;

  try {
    parsed = JSON.parse(fileContentsResult.value);
  } catch (cause) {
    return Either.left({
      message: `Repository storage at ${storagePath} is not valid JSON.`,
      cause
    });
  }

  const result = storageSchema.safeParse(parsed);

  if (!result.success) {
    return Either.left({
      message: `Repository storage at ${storagePath} does not match the schema.`,
      issues: result.error.issues
    });
  }

  return Either.right(result.data);
}

async function writeStorage<TStorageSchema extends z.ZodType>(
  storagePath: string,
  storage: z.output<TStorageSchema>
): Promise<Either<RepositoryError, void>> {
  const contents = `${JSON.stringify(storage, null, 2)}\n`;
  const walResult = await writeStorageWal(storagePath, contents, storage);

  if (Either.isLeft(walResult)) {
    return walResult;
  }

  return uploadStorage(storagePath, contents);
}

async function writeStorageWal(
  storagePath: string,
  contents: string,
  storageState: unknown
): Promise<Either<RepositoryError, void>> {
  const repositoryNameResult = getRepositoryNameFromStoragePath(storagePath);

  if (Either.isLeft(repositoryNameResult)) {
    return repositoryNameResult;
  }

  const repositoryName = repositoryNameResult.value;
  const timestamp = createWalTimestamp();
  const walPath = join(WAL_FOLDER_PATH, `${repositoryName}-${timestamp}.json`);
  const wal = {
    repositoryName,
    storagePath,
    createdAt: new Date().toISOString(),
    contents,
    storageState
  };

  try {
    await mkdir(WAL_FOLDER_PATH, { recursive: true });
    await writeFile(walPath, `${JSON.stringify(wal, null, 2)}\n`, 'utf8');
    await pruneStorageWal(repositoryName);

    return Either.right(undefined);
  } catch (cause) {
    return Either.left({
      message: `Failed to write repository WAL for ${storagePath}.`,
      cause
    });
  }
}

async function pruneStorageWal(repositoryName: string): Promise<void> {
  const now = Date.now();
  const entries = await readdir(WAL_FOLDER_PATH, { withFileTypes: true });
  const walFiles = entries
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .filter((fileName) => fileName.startsWith(`${repositoryName}-`) && fileName.endsWith('.json'));

  for (const oldFileName of walFiles) {
    const timestampResult = parseWalTimestamp(repositoryName, oldFileName);

    if (Either.isLeft(timestampResult) || now - timestampResult.value.getTime() <= WAL_RETENTION_MS) {
      continue;
    }

    await unlink(join(WAL_FOLDER_PATH, oldFileName));
  }
}

function getRepositoryNameFromStoragePath(storagePath: string): Either<RepositoryError, string> {
  if (!storagePath.startsWith(APP_FOLDER_PATH_PREFIX) || !storagePath.endsWith('.json')) {
    return Either.left(`Cannot derive repository name from storage path "${storagePath}".`);
  }

  const repositoryName = storagePath.slice(APP_FOLDER_PATH_PREFIX.length, -'.json'.length);

  if (!MODEL_NAME_PATTERN.test(repositoryName)) {
    return Either.left(`Repository storage path "${storagePath}" does not contain a valid name.`);
  }

  return Either.right(repositoryName);
}

function createWalTimestamp(): string {
  return new Date().toISOString().replace(/[:.]/g, '-');
}

function parseWalTimestamp(
  repositoryName: string,
  fileName: string
): Either<RepositoryError, Date> {
  const timestamp = fileName.slice(`${repositoryName}-`.length, -'.json'.length);
  const match = /^(\d{4}-\d{2}-\d{2})T(\d{2})-(\d{2})-(\d{2})-(\d{3})Z$/.exec(timestamp);

  if (match === null) {
    return Either.left(`WAL file "${fileName}" does not contain a valid timestamp.`);
  }

  const [, date, hours, minutes, seconds, milliseconds] = match;
  const parsed = new Date(`${date}T${hours}:${minutes}:${seconds}.${milliseconds}Z`);

  if (Number.isNaN(parsed.getTime())) {
    return Either.left(`WAL file "${fileName}" timestamp is not a valid date.`);
  }

  return Either.right(parsed);
}

function parseInputData<TSchema extends z.ZodObject>(
  data: z.input<TSchema>,
  schema: TSchema
): Either<RepositoryError, z.output<TSchema>> {
  const result = schema.safeParse(data);

  if (!result.success) {
    return Either.left({
      message: 'Repository input data does not match the schema.',
      issues: result.error.issues
    });
  }

  return Either.right(result.data);
}

function storageToRows<TSchema extends z.ZodObject>(
  storage: StorageMap<TSchema>
): StoredRow<TSchema>[] {
  return Object.keys(storage)
    .flatMap((key) => {
      const idResult = RepositoryIdSchema.safeParse(key);

      if (!idResult.success) {
        return [];
      }

      const entry = storage[idResult.data];

      if (entry === undefined) {
        return [];
      }

      return [
        {
          id: idResult.data,
          data: entry.data,
          createdAt: entry.createdAt
        }
      ];
    })
    .sort((left, right) => Date.parse(right.createdAt) - Date.parse(left.createdAt));
}

function createRepositoryId(): RepositoryId {
  return RepositoryIdSchema.parse(randomUUID());
}

async function downloadStorage(storagePath: string): Promise<Either<RepositoryError, string>> {
  const linkResult = await getYandexLink('/resources/download', { path: storagePath });

  if (Either.isLeft(linkResult)) {
    if (isYandexNotFoundError(linkResult.value)) {
      const createResult = await uploadStorage(storagePath, '{}\n');

      if (Either.isLeft(createResult)) {
        return createResult;
      }

      return Either.right('{}');
    }

    return linkResult;
  }

  try {
    const response = await fetch(linkResult.value.href);
    const body = await response.text();

    if (!response.ok) {
      return Either.left({
        message: `Failed to download repository storage from ${storagePath}.`,
        status: response.status,
        body
      });
    }

    return Either.right(body);
  } catch (cause) {
    return Either.left({
      message: `Network failure while downloading repository storage from ${storagePath}.`,
      cause
    });
  }
}

async function uploadStorage(
  storagePath: string,
  contents: string
): Promise<Either<RepositoryError, void>> {
  const linkResult = await getYandexLink('/resources/upload', {
    path: storagePath,
    overwrite: 'true'
  });

  if (Either.isLeft(linkResult)) {
    return linkResult;
  }

  try {
    const response = await fetch(linkResult.value.href, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json; charset=utf-8'
      },
      body: contents
    });
    const body = await response.text();

    if (!response.ok) {
      return Either.left({
        message: `Failed to upload repository storage to ${storagePath}.`,
        status: response.status,
        body
      });
    }

    return Either.right(undefined);
  } catch (cause) {
    return Either.left({
      message: `Network failure while uploading repository storage to ${storagePath}.`,
      cause
    });
  }
}

async function getYandexLink(
  path: string,
  params: Record<string, string>
): Promise<Either<RepositoryError, { href: string }>> {
  const tokenResult = getYandexToken();

  if (Either.isLeft(tokenResult)) {
    return tokenResult;
  }

  const url = new URL(`${YANDEX_DISK_API_BASE_URL}${path}`);

  for (const [key, value] of Object.entries(params)) {
    url.searchParams.set(key, value);
  }

  try {
    const response = await fetch(url, {
      headers: {
        Accept: 'application/json',
        Authorization: `OAuth ${tokenResult.value}`
      }
    });
    const body = await response.text();
    const parsed = parseOptionalJson(body);

    if (!response.ok) {
      return Either.left({
        message: `Yandex Disk API request failed for ${params.path}.`,
        status: response.status,
        yandex: Either.isRight(parsed) ? parsed.value : undefined,
        parseError: Either.isLeft(parsed) ? parsed.value : undefined
      });
    }

    if (Either.isLeft(parsed)) {
      return parsed;
    }

    const link = parsed.value as YandexLinkResponse;

    if (typeof link.href !== 'string' || link.href.length === 0) {
      return Either.left({
        message: `Yandex Disk API did not return a usable link for ${params.path}.`,
        response: parsed.value
      });
    }

    return Either.right({ href: link.href });
  } catch (cause) {
    return Either.left({
      message: `Network failure while requesting a Yandex Disk link for ${params.path}.`,
      cause
    });
  }
}

function getYandexToken(): Either<RepositoryError, string> {
  const envToken = process.env.YA_KEY?.trim();

  if (envToken !== undefined && envToken.length > 0) {
    return Either.right(envToken);
  }

  const envLocalTokenResult = readEnvLocalValue('YA_KEY');

  if (Either.isLeft(envLocalTokenResult)) {
    return envLocalTokenResult;
  }

  if (envLocalTokenResult.value.length === 0) {
    return Either.left('Missing Yandex Disk OAuth token. Set YA_KEY in the environment or .env.local.');
  }

  return Either.right(envLocalTokenResult.value);
}

function readEnvLocalValue(key: string): Either<RepositoryError, string> {
  const envLocalPath = join(process.cwd(), '.env.local');
  let contents: string;

  try {
    contents = readFileSync(envLocalPath, 'utf8');
  } catch (cause) {
    return Either.left({
      message: `Missing Yandex Disk OAuth token and failed to read ${envLocalPath}.`,
      cause
    });
  }

  for (const line of contents.split(/\r?\n/)) {
    const trimmedLine = line.trim();

    if (trimmedLine.length === 0 || trimmedLine.startsWith('#')) {
      continue;
    }

    const separatorIndex = trimmedLine.indexOf('=');

    if (separatorIndex === -1) {
      continue;
    }

    const name = trimmedLine.slice(0, separatorIndex).trim();

    if (name !== key) {
      continue;
    }

    return Either.right(unquoteEnvValue(trimmedLine.slice(separatorIndex + 1).trim()));
  }

  return Either.right('');
}

function unquoteEnvValue(value: string): string {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }

  return value;
}

function parseOptionalJson(body: string): Either<RepositoryError, unknown> {
  if (body.trim().length === 0) {
    return Either.right(undefined);
  }

  try {
    return Either.right(JSON.parse(body));
  } catch (cause) {
    return Either.left({
      message: 'Yandex Disk API returned a response that is not valid JSON.',
      body,
      cause
    });
  }
}

function isYandexNotFoundError(error: RepositoryError): boolean {
  if (!isObjectRecord(error)) {
    return false;
  }

  if (error.status === 404) {
    return true;
  }

  const yandex = error.yandex;

  if (!isObjectRecord(yandex)) {
    return false;
  }

  const yandexError = yandex as YandexErrorResponse;

  return (
    yandexError.error === 'DiskNotFoundError' ||
    yandexError.error === 'DiskPathDoesntExistsError' ||
    yandexError.error === 'DiskResourceNotFoundError'
  );
}

function isObjectRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}
